### ISSUE TITLE
speed test in whitelist

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#1]
I just find the last one is slower than before in speed test  at whitelist under same vps 
by the way ,I like your luci-ssr,I'm usring it

**Comment by honwen** [comment]
whitelist means chn route?

is the Physical distance of test SERVER and Ur VPS close enough?

Probably U should check DNS

**Comment by jack338c** [comment]
yes,chnrouter
I use http://www.speedtest.net/ find download speed is different.so currenlty  I'm use your previous commit to build,it's more faster,but I don't why

**Comment by honwen** [comment]
which commit R U using?

**Comment by jack338c** [comment]
e4d8db412d4e97c6f4f9bdade19fc97550a6e356

**Comment by honwen** [comment]
Maybe it's becase i enable chinadns's bidirectional,
because YTB's ip check url using```http://redirector.googlevideo.com/report_mapping```.

if dont enable chinadns's bidirectional, ```redirector.googlevideo.com``` may be resolve to ip in beijing. This cause YTB problem.

**Comment by jack338c** [comment]
ok, I got it,thank you for replys and patience!
