### ISSUE TITLE
dns issue

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#10]
hi chen
I find it's hard to open website-Facebook on pc but phone is ok ,and ssr client on pc is ok too
Could you give me some tips to solve this

thanks
by the way I use dnsmasq-extra +chinadns+dnsforward

**Comment by honwen** [comment]
try: ```dnsmasq-extra + dnscrypt```

**Comment by jack338c** [comment]
I just tested,it's same---hard to disaplay pictures on website and can't play videos
and I feel dnsmasq-extra +chinadns is more smooth on opening github site.it's just feel 

thanks

by the way use padavan RT-AC54U (rampis 7260)  router is also no problem on facebook

**Comment by honwen** [comment]
open facebook with chrome, and watch log in ```network``` tag of dev panel (F12)

find the red ones

**Comment by jack338c** [comment]
yes, I do find a lots of red ones,what's the next step?

**Comment by jack338c** [comment]
the redones are all like yyyyyyyy.xx.fbcdn.net

I tried Global proxy,but stil dos't work

**Comment by honwen** [comment]
list all the domain names

**Comment by jack338c** [comment]
all the red domains have the  same postfix--xx.fbcdn.net, is that ok?
the domain names is complex ,they are like 10000000_444696075986936_ ...etc

**Comment by honwen** [comment]
nslookup them to check its ip if is correct.

**Comment by jack338c** [comment]
I check it on ip.cn ,it shows 

您查询的 IP：157.240.22.35

所在地理位置：美国 Facebook

by the way,do you have same issue on facebook? or maybe just my network problem?

**Comment by honwen** [comment]
where is ur vps. it's totally ok if ur vps is in USA

**Comment by jack338c** [comment]
I'm using usa one too,so it's my problem,I will check it out later
you are the best ,many thenks

**Comment by jack338c** [comment]
I put the newest China router  file at /etc .that's why I can't open Facebook
My bad 
Sorry

**Comment by honwen** [comment]
no need to update manually. ```dnsmasq-extra``` will auto-update itself once a week

**Comment by honwen** [comment]
Refer: https://github.com/chenhw2/openwrt-dnsmasq-extra/blob/master/dnsmasq-extra/files/sh/uci-defaults#L4

**Comment by jack338c** [comment]
thank you chen
I was wrong ,the other real reason is I removed fbcdn.com from gfwlist  which locate in /etc/dnsmasq-extra.d.
I add fbcdn.com to gfwlist.now ,everything is fine
but I can't understand,I'm using chinarouter model not gfwlist model,it shoul not matter

**Comment by honwen** [comment]
All DNS request are hijacked to router, in case not all client's DNS are correct.

**Comment by jack338c** [comment]
OK I got it 
Have a good rest
