### ISSUE TITLE
关于2.0.16的dnscrypt的下载问题

### ISSUE THREAD

**Issue by thisdk** [honwen/openwrt-dnsmasq-extra#11]
作者你好.我在编译这个库的时候遇到一个问题.

编译环境: Ubuntu 18.04 Server
编译系统: OpenWrt 18.06 ramips mt7621 k2p
遇到问题: dnscrypt下载失败.

log:

`
time: package/system/ca-certificates/compile#0.11#0.08#0.16
make[3]: Entering directory '/home/thisdk/k2p/openwrt/package/feeds/openwrt-dnsmasq-extra/dnscrypt'
mkdir -p /home/thisdk/k2p/openwrt/dl
SHELL= flock /home/thisdk/k2p/openwrt/tmp/.dnscrypt-proxy-linux_mipsel-2.0.16.tar.gz.flock -c '  	/home/thisdk/k2p/openwrt/scripts/download.pl "/home/thisdk/k2p/openwrt/dl" "dnscrypt-proxy-linux_mipsel-2.0.16.tar.gz" "skip" "" "https://github.com/jedisct1/dnscrypt-proxy/releases/download/2.0.16/"    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://github.com/jedisct1/dnscrypt-proxy/releases/download/2.0.16/dnscrypt-proxy-linux_mipsel-2.0.16.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.lede-project.org/dnscrypt-proxy-linux_mipsel-2.0.16.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror2.openwrt.org/sources/dnscrypt-proxy-linux_mipsel-2.0.16.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://downloads.openwrt.org/sources/dnscrypt-proxy-linux_mipsel-2.0.16.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    120      0  0:00:01  0:00:01 --:--:--   120
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.
Makefile:42: recipe for target '/home/thisdk/k2p/openwrt/dl/dnscrypt-proxy-linux_mipsel-2.0.16.tar.gz' failed
make[3]: *** [/home/thisdk/k2p/openwrt/dl/dnscrypt-proxy-linux_mipsel-2.0.16.tar.gz] Error 2
make[3]: Leaving directory '/home/thisdk/k2p/openwrt/package/feeds/openwrt-dnsmasq-extra/dnscrypt'
Command exited with non-zero status 2
time: package/feeds/openwrt-dnsmasq-extra/dnscrypt/compile#0.18#0.09#6.39
package/Makefile:107: recipe for target 'package/feeds/openwrt-dnsmasq-extra/dnscrypt/compile' failed
make[2]: *** [package/feeds/openwrt-dnsmasq-extra/dnscrypt/compile] Error 2
make[2]: Leaving directory '/home/thisdk/k2p/openwrt'
package/Makefile:103: recipe for target '/home/thisdk/k2p/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/thisdk/k2p/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/thisdk/k2p/openwrt'
/home/thisdk/k2p/openwrt/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2
`

我看了log后发现问题所在是下载连接错了.

/releases/download/2.0.16/dnscrypt-proxy-linux_mipsle-2.0.16.tar.gz
/releases/download/2.0.16/dnscrypt-proxy-linux_mipsel-2.0.16.tar.gz

具体错在mipsle这个字母

**Comment by honwen** [comment]
Refer: https://superuser.com/questions/1262144/naming-mipsle-vs-mipsel

Try latest commit: https://github.com/chenhw2/openwrt-dnsmasq-extra/commit/072b45ec10670787ddbb62fcb0ffdc862b0e6da5

**Comment by thisdk** [comment]
谢谢你修复了这个问题.还写出了那么好的库.几个套件我都编译到固件里面了.用起来十分舒服
