### ISSUE TITLE
dnsmasq-extra 的 adblock 部分是强制过滤的？

### ISSUE THREAD

**Issue by laincat** [honwen/openwrt-dnsmasq-extra#12]
这几天在使用大大的这套方案，发现有些地址被强制 0.0.0.0 后。。。查了很久。。。

**Comment by laincat** [comment]
另外问下 https://github.com/aa65535/openwrt-dist-luci 像这个界面包，好像对 openwrt-dnsmasq-extra
 里的组件是无效的？

**Comment by honwen** [comment]
这里的组件改过不兼容https://github.com/aa65535/openwrt-dist-luci
有些adblock误杀的话麻烦反馈

**Comment by laincat** [comment]
不不，原本我以为没有安装 https://github.com/chenhw2/luci-app-koolproxy ，就没有加载去广告功能，还以为我网络出状况了。

然后我砍了

`echo -n "ABDLOCK, " && ( sed "s/^/address=\//;s/$/\/${BLOCK}/" $IPSETDIR/adblock > $DNSMASQDIR/adblock.conf )`

**Comment by honwen** [comment]
这两个广告过滤是独立的

**Comment by laincat** [comment]
嗯嗯，我现在弄明白了。大大的方案很稳，用得最舒服了。谢谢
