### ISSUE TITLE
dns pollution

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#13]
today I can not open google.com ,if use dnsmasq-extra + chinadns (+cdns +dns-forwarder) on Chinamobile(ISP),but on Chinatelecom is ok

if use dnsmasq-extra + dnscrypt ,everything is ok

How can I let chinadns worked on Chinamobile,where should I modify ?

thanks Chen

**Comment by honwen** [comment]
try delete the lines with `:53` in `/etc/config/chinadns` and retart chinadns

**Comment by jack338c** [comment]
now it works !
many thanks :smiley:

**Comment by jack338c** [comment]
Hi chen,I found you have update commit,but I have to be honest tell you.today the issue has come back.I can't open google.com again ,other sites are ok

**Comment by honwen** [comment]
@jack338c  Can U provide a Chinamobile environment for me to test

**Comment by jack338c** [comment]
@chenhw2 
I did not know how to show you the environment,I'm located in Ningbo

and I try restore to list ww_dns '4.2.2.2:53' then restart chinadns,it works again

I wonder maybe my router has problem

let me test more and more then tell you later

sorry

**Comment by jack338c** [comment]
hi@chenhw2 ,I have tested,it's my firmware problem :stuck_out_tongue_winking_eye: 
maybe you should  revert your commit
thanks

**Comment by jack338c** [comment]
hi @chenhw2 
I found this in the system log finally
"daemon.warn dnsmasq[2157]: possible DNS-rebind attack detected: www.google.com"

I have 2 ISPs,one is china mobile the other is china telecom,both use pppoe model
same openwrt router,same firmware with your repository

the china mobile one will get above log then www.google.com got killed

here is my cmcc dns info
DNS 1: 211.140.13.188
DNS 2: 211.140.188.188

I try use following meths,but it dosen't work

Allow rebind responses RFC1918 (In LUCI goto Network → DHCP and DNS and uncheck Rebind protection checkmark)
Add google.com domain to Whitelist (In LUCI goto Network → DHCP and DNS and type in “google.com” without quotes to the Domain whitelist field

**Comment by honwen** [comment]
it seems that cmcc dns pollution is more critical than excepted, use `dnscrypt` instead with cmcc

**Comment by jack338c** [comment]
yes,it's possiable
Fortunately you give an alternative :+1: 
thanks :smile:

**Comment by honwen** [comment]
@jack338c  `dnscrypt` can provide a promised correct DNS, but not always the best(low latency) DNS

**Comment by jack338c** [comment]
@chenhw2 
ok,I got it
many thanks

**Comment by jack338c** [comment]
@chenhw2 
 facebook and google could't be open now by chinadns one on chinamobile or chinaunicom
no reply,just let you know

**Comment by honwen** [comment]
@jack338c probably caused by `Two sessions`

**Comment by jack338c** [comment]
Hi Chen
Today I found CHINDNS works fine on my Chinamobile network
but I wonder if We can change some value to fix this in /etc/init.d/chinadns ?
like  following value or Could you give me an idea? 
193.112.15.186
101.132.183.99
80.80.80.80
9.9.9.9

thanks

**Comment by honwen** [comment]
![2019-04-12 23-47-25屏幕截图](https://user-images.githubusercontent.com/12322033/56050018-5f23fd00-5d7d-11e9-8f44-bd7bb7fb2a92.png)

remove these line by line and test if it works

**Comment by jack338c** [comment]
ok,I will
Thank you very much !

**Comment by jack338c** [comment]
I tested it.It works for the moment.
Cool :clinking_glasses:

**Comment by honwen** [comment]
It seems that cdns(https://github.com/semigodking/cdns) not working now

**Comment by jack338c** [comment]
I'm not sure,cause I almost didn't use udp function.
but just now I enable UDP-Relay Server and use nat tools to verify it.it's working

**Comment by honwen** [comment]
with dnsmasq-extra, u can just use ss-tunnel as dns server

**Comment by jack338c** [comment]
ok,I got it
thanks for your exprt knowledge !
