### ISSUE TITLE
staticfile.org is in direct list but excluding *.staticfile.org

### ISSUE THREAD

**Issue by stevenjohn2019** [honwen/openwrt-dnsmasq-extra#14]
Domain staticfile.org is in direct list. However, any *.staticfile.org domain like cdn.staticfile.org will be resolved via ssr-tunnel. It should be resolved via domestic DNS server.
So it result in a problem that any website using staticfile.org resources loads slowly, and sometimes loads fail with timeout, because it resolved to other country.

**Comment by honwen** [comment]
try latest commit

**Comment by stevenjohn2019** [comment]
I have already reinstalled the latest commit version with --force-reinstall option.
But now the problem isn't be solved.
Both staticfile.org and *.staticfile.org are resolved via ssr-tunnel.

I set gfwlist mode in ssr setting which list that option wan_bp_list '/dev/flag_gfwlist', and it doesn't create the /var/dnsmasq.d/ipset_direct.conf file.

**Comment by honwen** [comment]
`direct` only work with chnroute, by design

**Comment by stevenjohn2019** [comment]
In gfwlist mode, domain *.staticfile.org is not in gfwlist,. However, why is cdn.staticfile.org resolved via ssr-tunnel?

**Comment by honwen** [comment]
`.org` Was put in `dnsmasq-extra/files/data/tldn` to ensure dns is always clean.

if `staticfile.org` is so special, it's ok to put in `dnsmasq-extra/files/data/custom.conf`

**Comment by honwen** [comment]
usually, domain of CDN is `.com`

**Comment by honwen** [comment]
try latest commit
