### ISSUE TITLE
how to deal with playstore in Chinadns chnroute model

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#15]
Hi 
hope everything is ok to you
I meet the issue like this,but in gfwlist model is ok
https://github.com/shadowsocks/luci-app-shadowsocks/issues/174

Can I just add following to custom.conf?

#for Play store
ipset=/services.googleapis.cn/ss_spec_dst_fw
server=/services.googleapis.cn/=127.0.0.1#7300

but it's failed 
thanks

**Comment by honwen** [comment]
try latest commit, and add `203.208.32.0/19` to here
![2019-07-22 00-54-44屏幕截图](https://user-images.githubusercontent.com/12322033/61594217-c292b600-ac1b-11e9-979b-4aeeb8fcef97.png)

**Comment by jack338c** [comment]
ok,I got it
will test it and  give you a feedback
many thanks

**Comment by jack338c** [comment]
@honwen  you great ,It works !!
thanks again
