### ISSUE TITLE
支持直接使用dns-forwarder

### ISSUE THREAD

**Issue by smaller09** [honwen/openwrt-dnsmasq-extra#16]
能不能直接支持dns-forwarder，方式是gfwlist内的域名直接通过dns-forwarder来解释，dns-forwarder则把域名请求转为tcp通过ssr隧道转发出去，目前udp的域名解释在各大运营商上受限严重，这个模式会不会轻量一些，我目前修改了你的代码就这样使用。感觉还行

**Comment by honwen** [comment]
Good idea

**Comment by honwen** [comment]
try https://github.com/honwen/openwrt-dnsmasq-extra/commit/95a4396285cee12ec094630351716fbee0a36e76

**Comment by smaller09** [comment]
我看你的实现方式，没细看和测试，如果没错的话，应该是gfwlist的域名请求通过dns-forwarder转换为tcp，然后用ssr-tunnel转发。我觉得ssr-tunnel没必要启动了，我是dns-forwarder的上游地址设置为8.8.8.8，然后设置8.8.8.8为强制代理地址，这样ssr-redir就直接转发出去了，不再需要ssr-tunnel了

**Comment by honwen** [comment]
兼容开/不开tunnel, 兼容开/不开redir, 以更好兼容性为主, dns-forwarder的性能要求很低, 多开几个没关系
