### ISSUE TITLE
hard to open site "Netflix"

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#17]
HI,honwen
Today I found it's hard to open site "Netflix" in Chinaroute model,sometime gets slow and sometime gets "This page isn’t working www.netflix.com redirected you too many times.Try clearing your cookies."

I tried fall back your previous Commits and rebuild package,but it's not working

when I try "merlin-xiaobao" on another router to open site "Netflix",everything is ok

I don't why,and I'm not sure it's my problem or not

thanks

**Comment by jack338c** [comment]
my bad

**Comment by jack338c** [comment]
the issue still exist on pc ,it's unstable,neither on chrome or internet Explorer,but app and  chrome can open it ,but can't play,it seems bypass ssr stock
Could you check it out later
thanks

**Comment by jack338c** [comment]
I also found no plugin_xx.conf in /var/dnsmasq.d neither on chinaroute or gfwlist model

**Comment by jack338c** [comment]
just now I found another interesting thing: if I remove" ipset=/bitz.com/ssr_spec_dst_bp" in custom.conf.netflix will works,otherwize it's failed

ps: bitz.com works on no shadowsocks,So I put it to custom.conf

**Comment by jack338c** [comment]
new found: it will works for netflix after restart dnsmasq-extra everytime

**Comment by jack338c** [comment]
New found: it works on dhcp model of my another openwrt, the issues occur on pppoe  model of my  previous openwrt router which  have many SSR nodes inside

**Comment by honwen** [comment]
cant reproduce, works fine in my another pppoe mode router

**Comment by jack338c** [comment]
I guess maybe is the ISP problem,It desn't matter,I switchto dhcp now

thank you for your time
