### ISSUE TITLE
openwrt-dnsmasq-extra能与lean的ssr-plus配合吗？

### ISSUE THREAD

**Issue by shenzt68** [honwen/openwrt-dnsmasq-extra#18]
如题？
你这个很好用，就想它与ssr-plus能配合就好了。
请指教！

**Comment by honwen** [comment]
理论上可行 但是不想去跟ssr-plus的逻辑实现

**Comment by shenzt68** [comment]
直接用你的ssr，但没集成v2ray啊？也没订阅功能吧？

**Comment by honwen** [comment]
> 直接用你的ssr，但没集成v2ray啊？也没订阅功能吧？

没集成 也没打算做订阅, 这不符合`KISS principle`
