### ISSUE TITLE
和v2有冲突

### ISSUE THREAD

**Issue by hcym** [honwen/openwrt-dnsmasq-extra#19]
extra和v2ray不能并存，请教是不是要做什么规则改变？

**Comment by honwen** [comment]
Cant NOT Reproduce

**Comment by hcym** [comment]
用了两个luci的V2都试了试，应该是国内dns冲突，记得以前的还没有adguard的老版本没有问题，算了，不用v2也行，目前都是机场大巴。谢谢啦
