### ISSUE TITLE
advise

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#2]
Could you try use dnsproxy instead of pdnsd,it's more lightweight and faster

here is the code and makefile,but I can not do it,maybe you can,thanks

http://www.right.com.cn/forum/thread-215830-1-1.html

**Comment by honwen** [comment]
```pdnsd``` should be deprecated, please try ```chinadns + dns-forwarder```.

This repository mainly focus on provide clean dns without other dependcy (socks proxy or ss proxy).

Does U mean ```openwrt-Pcap_DNSProxy```, it seams need a socks proxy to work?

**Comment by jack338c** [comment]
ok,now I understand,thank you
it's not openwrt-Pcap_DNSProxy, just DNSProxy,a new cache tech

**Comment by honwen** [comment]
U mean https://github.com/zhengxinhn/dnsproxy ?

**Comment by jack338c** [comment]
yes.it is!
