### ISSUE TITLE
如何设置指定IP走代理,其他的不做处理

### ISSUE THREAD

**Issue by thisdk** [honwen/openwrt-dnsmasq-extra#21]
作者你好
我现在使用您的插件包组合,现在因为某些原因.想指定特定的IP段走代理,其他不做处理
插件组合是 : dnsmasq-extra + chinadns (+cdns +dns-forwarder) + ss
我试过访问控制哪里的几个选项,都没有符合我想要的那种.请问我需要怎么设置.
IP段如下:
13.112.0.0/16
34.192.0.0/16
52.196.0.0/16
54.64.0.0/16
54.182.0.0/16
151.101.72.0/24
168.95.245.0/24
202.80.104.0/24
202.80.107.0/24
类似这种.

thanks!

**Comment by honwen** [comment]
report to [luci-app-shadowsocks](https://github.com/shadowsocks/luci-app-shadowsocks/issues) instead.
