### ISSUE TITLE
want connect githubusercontent.com direclty

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#22]
Hi my idol
I need you help
I trid put githubusercontent.com to /etc/dnsmasq-extra.d/direct or /etc/dnsmasq-extra.d/custom.conf,but neither of them works
For some reasons I want githubusercontent.com bypass proxy

thank you and have a nice day :smiley:

**Comment by honwen** [comment]
### custom.conf
delete:
```
ipset=/githubusercontent.com/gfwlist
```

add:
```
ipset=/githubusercontent.com/ss_spec_dst_bp
ipset=/raw.githubusercontent.com/ss_spec_dst_bp
ipset=/githubusercontent.com/ssr_spec_dst_bp
ipset=/raw.githubusercontent.com/ssr_spec_dst_bp
```

**Comment by jack338c** [comment]
Thanks for fast response
I added it ,but still get failed 
currenlty I use dnsmasq-extra + chinadns (+cdns +dns-forwarder)

Openwrt Router (Self Proxy) can't Resolving raw.githubusercontent.com and wget: unable to resolve host address 'raw.githubusercontent.com'

my test condition: power off vps temporarily for ssr

**Comment by honwen** [comment]
add:
```
server=/.githubusercontent.com/8.8.8.8
server=/.githubusercontent.com/119.29.107.85#9090
server=/.githubusercontent.com/107.155.79.120#9090
server=/raw.githubusercontent.com/8.8.8.8
server=/raw.githubusercontent.com/119.29.107.85#9090
server=/raw.githubusercontent.com/107.155.79.120#9090
```

**Comment by jack338c** [comment]
It's workging !!! you never make me down.
Thanks a lot for your support :clinking_glasses:

**Comment by jack338c** [comment]
it's weird,yesterday I did make it,then go away,
Today I try do it again, but now it's failed ,same network,same ISP,same router
I have reset my openwrt router to factory several times
thanks for your time :smiley: 

root@LEDE:~ wget https://raw.githubusercontent.com/honwen/openwrt-dnsmasq-extra/master/dnsmasq-extra/files/data/custom.conf
--2019-12-11 09:53:47--  https://raw.githubusercontent.com/honwen/openwrt-dnsmasq-extra/master/dnsmasq-extra/files/data/custom.conf
Resolving raw.githubusercontent.com... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com|151.101.0.133|:443... connected.
Unable to establish SSL connection.


**custom.conf**

# For TeamViewer
ipset=/githubusercontent.com/ss_spec_dst_bp
ipset=/raw.githubusercontent.com/ss_spec_dst_bp
ipset=/githubusercontent.com/ssr_spec_dst_bp
ipset=/raw.githubusercontent.com/ssr_spec_dst_bp
ipset=/bitz.com/ssr_spec_dst_bp
ipset=/teamviewer.com/ss_spec_dst_bp
ipset=/teamviewer.com/ssr_spec_dst_bp
ipset=/dyngate.com/ss_spec_dst_bp
ipset=/dyngate.com/ssr_spec_dst_bp
ipset=/tvcdn.de/ss_spec_dst_bp
ipset=/tvcdn.de/ssr_spec_dst_bp

# For Github
ipset=/github.io/gfwlist
ipset=/amazonaws.com/gfwlist

# For SS(R) Watchdog
server=/accounts.gstatic.com/112.121.178.187

# For PPA:dl.google.com
server=/dl.google.com/127.0.0.1#7400
server=/dl.google.com/9.9.9.9
server=/dl.google.com/168.95.1.1
server=/dl.google.com/202.14.67.4
server=/dl.google.com/112.121.178.187

# For googleapis.cn
server=/googleapis.cn/127.0.0.1#7400
server=/googleapis.cn/9.9.9.9
server=/googleapis.cn/168.95.1.1
server=/googleapis.cn/202.14.67.4
server=/googleapis.cn/112.121.178.187

# For CDNs
server=/staticfile.org/#
server=/staticfile.org/114.114.115.115
server=/staticfile.org/182.254.116.116
server=/jsdelivr.net/#
server=/jsdelivr.net/114.114.115.115
server=/jsdelivr.net/182.254.116.116

# For ADs
address=/hao.centbrowser.cn/0.0.0.0

# Forgithub
server=/.githubusercontent.com/8.8.8.8
server=/.githubusercontent.com/119.29.107.85#9090
server=/.githubusercontent.com/107.155.79.120#9090
server=/raw.githubusercontent.com/8.8.8.8
server=/raw.githubusercontent.com/119.29.107.85#9090
server=/raw.githubusercontent.com/107.155.79.120#9090

**Comment by honwen** [comment]
combine **two** `add` together

**Comment by jack338c** [comment]
I add them togther like following .still get same result,it's interesting
if I disable ssrserver in my op router,wget from github will be ok

#For TeamViewer
ipset=/githubusercontent.com/ss_spec_dst_bp
ipset=/raw.githubusercontent.com/ss_spec_dst_bp
ipset=/githubusercontent.com/ssr_spec_dst_bp
ipset=/raw.githubusercontent.com/ssr_spec_dst_bp
server=/.githubusercontent.com/8.8.8.8
server=/.githubusercontent.com/119.29.107.85#9090
server=/.githubusercontent.com/107.155.79.120#9090
server=/raw.githubusercontent.com/8.8.8.8
server=/raw.githubusercontent.com/119.29.107.85#9090
server=/raw.githubusercontent.com/107.155.79.120#9090

#For Github
ipset=/github.io/gfwlist
ipset=/amazonaws.com/gfwlist
.....

#For TeamViewer
server=/.githubusercontent.com/8.8.8.8
server=/.githubusercontent.com/119.29.107.85#9090
server=/.githubusercontent.com/107.155.79.120#9090
server=/raw.githubusercontent.com/8.8.8.8
server=/raw.githubusercontent.com/119.29.107.85#9090
server=/raw.githubusercontent.com/107.155.79.120#9090
ipset=/githubusercontent.com/ss_spec_dst_bp
ipset=/raw.githubusercontent.com/ss_spec_dst_bp
ipset=/githubusercontent.com/ssr_spec_dst_bp
ipset=/raw.githubusercontent.com/ssr_spec_dst_bp

#For Github
ipset=/github.io/gfwlist
ipset=/amazonaws.com/gfwlist
.....

**Comment by honwen** [comment]
any log?

**Comment by jack338c** [comment]
Now is ok again,I just tested it to collect logs for you
I'll keep watch 
talk to you later

here is my custom.conf

# For TeamViewer
server=/.githubusercontent.com/8.8.8.8
server=/.githubusercontent.com/119.29.107.85#9090
server=/.githubusercontent.com/107.155.79.120#9090
server=/raw.githubusercontent.com/8.8.8.8
server=/raw.githubusercontent.com/119.29.107.85#9090
server=/raw.githubusercontent.com/107.155.79.120#9090
ipset=/githubusercontent.com/ss_spec_dst_bp
ipset=/raw.githubusercontent.com/ss_spec_dst_bp
ipset=/githubusercontent.com/ssr_spec_dst_bp
ipset=/raw.githubusercontent.com/ssr_spec_dst_bp
ipset=/bitz.com/ssr_spec_dst_bp
ipset=/teamviewer.com/ss_spec_dst_bp
ipset=/teamviewer.com/ssr_spec_dst_bp
ipset=/dyngate.com/ss_spec_dst_bp
ipset=/dyngate.com/ssr_spec_dst_bp
ipset=/tvcdn.de/ss_spec_dst_bp
ipset=/tvcdn.de/ssr_spec_dst_bp

# For Github
ipset=/github.io/gfwlist
ipset=/amazonaws.com/gfwlist

# For SS(R) Watchdog
server=/accounts.gstatic.com/112.121.178.187

# For PPA:dl.google.com
server=/dl.google.com/127.0.0.1#7400
server=/dl.google.com/9.9.9.9
server=/dl.google.com/168.95.1.1
server=/dl.google.com/202.14.67.4
server=/dl.google.com/112.121.178.187

# For googleapis.cn
server=/googleapis.cn/127.0.0.1#7400
server=/googleapis.cn/9.9.9.9
server=/googleapis.cn/168.95.1.1
server=/googleapis.cn/202.14.67.4
server=/googleapis.cn/112.121.178.187

# For CDNs
server=/staticfile.org/#
server=/staticfile.org/114.114.115.115
server=/staticfile.org/182.254.116.116
server=/jsdelivr.net/#
server=/jsdelivr.net/114.114.115.115
server=/jsdelivr.net/182.254.116.116

# For ADs
address=/hao.centbrowser.cn/0.0.0.0

**Comment by jack338c** [comment]
Currently it's not stable,now it's failed again
Acctually I  found if https://github.com/honwen/openwrt-dnsmasq-extra can be open by web browse,then wget from github will be fine

Here is the system log from my openwrt rouer,thanks

Wed Dec 11 23:01:11 2019 daemon.info dnsmasq[2033]: using standard nameservers for domain yupoo.com
Wed Dec 11 23:01:11 2019 daemon.info dnsmasq[2033]: using standard nameservers for domain yunshipei.com
Wed Dec 11 23:01:11 2019 daemon.info dnsmasq[2033]: using standard nameservers for domain yundaex.com
Wed Dec 11 23:01:11 2019 daemon.info dnsmasq[2033]: using standard nameservers for domain yunba.io
Wed Dec 11 23:01:11 2019 daemon.info dnsmasq[2033]: using standard nameservers for domain yts.ag
Wed Dec 11 23:01:11 2019 daemon.info dnsmasq[2033]: using standard nameservers for domain ysten.com
Wed Dec 11 23:01:11 2019 daemon.info dnsmasq[2033]: using standard nameservers for domain youtube-mp3.org
Wed Dec 11 23:01:11 2019 daemon.info dnsmasq[2033]: using standard nameservers for domain youm7.com
Wed Dec 11 23:01:11 2019 daemon.info dnsmasq[2033]: using 7884 more nameservers
Wed Dec 11 23:01:11 2019 daemon.info dnsmasq[2033]: read /etc/hosts - 4 addresses
Wed Dec 11 23:01:11 2019 daemon.info dnsmasq[2033]: read /tmp/hosts/dhcp.cfg02411c - 1 addresses
Wed Dec 11 23:01:11 2019 daemon.info dnsmasq-dhcp[2033]: read /etc/ethers - 0 addresses
Wed Dec 11 23:01:13 2019 daemon.err cdns[2090]: 1576076473.147643 cfg.c:44 cfg_loads(...) Failed to parse JSON content!
Wed Dec 11 23:01:13 2019 kern.info ssr-redir[2088]: initializing ciphers... rc4-md5
Wed Dec 11 23:01:13 2019 kern.info ssr-redir[2088]: tcp port reuse enabled
Wed Dec 11 23:01:13 2019 kern.info ssr-redir[2088]: listening at 0.0.0.0:1234
Wed Dec 11 23:01:13 2019 kern.info ssr-redir[2088]: running from root user
Wed Dec 11 23:01:18 2019 daemon.err cdns[2191]: 1576076478.157570 cfg.c:44 cfg_loads(...) Failed to parse JSON content!
Wed Dec 11 23:01:23 2019 daemon.err cdns[2192]: 1576076483.168761 cfg.c:44 cfg_loads(...) Failed to parse JSON content!
Wed Dec 11 23:01:28 2019 daemon.err cdns[2193]: 1576076488.179762 cfg.c:44 cfg_loads(...) Failed to parse JSON content!
Wed Dec 11 23:01:28 2019 daemon.info procd: Instance chinadns::instance4 s in a crash loop 6 crashes, 0 seconds since last crash
Wed Dec 11 23:04:05 2019 daemon.info hostapd: wlan0-1: STA 00:24:d7:34:99:94 IEEE 802.11: authenticated
Wed Dec 11 23:04:05 2019 daemon.info hostapd: wlan0-1: STA 00:24:d7:34:99:94 IEEE 802.11: associated (aid 1)
Wed Dec 11 23:04:05 2019 daemon.notice hostapd: wlan0-1: AP-STA-CONNECTED 00:24:d7:34:99:94
Wed Dec 11 23:04:05 2019 daemon.info hostapd: wlan0-1: STA 00:24:d7:34:99:94 RADIUS: starting accounting session DC8D379334B1E9EB
Wed Dec 11 23:04:05 2019 daemon.info hostapd: wlan0-1: STA 00:24:d7:34:99:94 WPA: pairwise key handshake completed (RSN)
Wed Dec 11 23:04:05 2019 daemon.info dnsmasq-dhcp[2033]: DHCPREQUEST(br-lan) 192.168.4.236 00:24:d7:34:99:94 
Wed Dec 11 23:04:05 2019 daemon.info dnsmasq-dhcp[2033]: DHCPACK(br-lan) 192.168.4.236 00:24:d7:34:99:94 jackl

**Comment by jack338c** [comment]
hi,honwen
I found if I remove following items,it will be more stable
but I'm not sure whether it will occurt other issue or not ?
thanks

server=/raw.githubusercontent.com/119.29.107.85#9090
server=/raw.githubusercontent.com/107.155.79.120#9090
server=/.githubusercontent.com/119.29.107.85#9090
server=/.githubusercontent.com/107.155.79.120#9090

**Comment by honwen** [comment]
> hi,honwen
> I found if I remove following items,it will be more stable
> but I'm not sure whether it will occurt other issue or not ?
> thanks
> 
> server=/raw.githubusercontent.com/119.29.107.85#9090
> server=/raw.githubusercontent.com/107.155.79.120#9090
> server=/.githubusercontent.com/119.29.107.85#9090
> server=/.githubusercontent.com/107.155.79.120#9090

U can any DNS server as U like, like anyone in https://dns.iui.im/

**Comment by jack338c** [comment]
ok, I got it
Thanks again for your help :handshake:
