### ISSUE TITLE
如何指定DoH服务器解析DNS请求

### ISSUE THREAD

**Issue by BlueHandsSpirits** [honwen/openwrt-dnsmasq-extra#23]
你好，还是我。

之前重启了一下openwrt，DNS突然失效，在没有连接ssr的情况下网页都打不开。我把openwrt恢复到初始状态，把软件包一个个重新装了一下（包括forward\dnsmasq-extra\dnscrypt）。DNS测出来的结果是本地解析，我想让它都走geekdns，我想分为2步：把解析服务器只留一个geekdns、把DNS解析请求都转发到DoH服务器。

1：把 /etc/init.d/dnscrypt 下的源只留了 public-resolvers ，并在 /etc/dnscrypt.d 下把 public-resolvers.md 的服务器列表只留了一个 geekdns ，并删除了两个文件中的更新网址，我这样做对吗？

![1](https://user-images.githubusercontent.com/58907334/71080757-bf9af200-21c8-11ea-90ff-44fb1df356d0.png)

![2](https://user-images.githubusercontent.com/58907334/71080765-c45fa600-21c8-11ea-8a00-23a7144aca12.png)

2：配置文件我不大能看得懂，我想找到dnscrypt的地址和端口，但是没找到地址（只找到端口7400），不知道该怎么写DNS转发地址，还请指教。

：）

**Comment by honwen** [comment]
address: `0.0.0.0`

**Comment by honwen** [comment]
U can hardcode Ur upstearm dns server in `/etc/config/dnscrypt`, like https://github.com/honwen/openwrt-dnsmasq-extra/blob/master/dnscrypt/files/dnscrypt.conf#L11

**Comment by BlueHandsSpirits** [comment]
我把“#”去掉并把地址替换成我想要的，dns转发地址填为“0.0.0.0”，可依然无效，系统日志报错 “cron.info crond[1706]: USER root pid 2695 cmd /usr/bin/pgrep -f dnscrypt.toml || /etc/init.d/dnscrypt restart”，接下来该怎么做？

**Comment by honwen** [comment]
google config of `dnsmasq` and `crontab` Urself

**Comment by BlueHandsSpirits** [comment]
问题已解决，感谢！
