### ISSUE TITLE
关于smartdns如何使用的问题

### ISSUE THREAD

**Issue by thisdk** [honwen/openwrt-dnsmasq-extra#25]
大佬你好.又打扰了.
我使用了你推荐的dnsmasq-extra + smartdns组合
源码使用openwrt 18.06
编译刷机后.根据smartdns文档所说.若是成功启用,
nslookup 查询出来的IP只有一个地址
可是我nslookup出来基本都有2个地址
然后我手动把DHCP/DNS那里的DNS转发设置为127.0.0.1#7700后
我通过跟踪日志.确实是产生了日志.但是仍然返回了2个IP.
我电脑重启还有刷新DNS记录或者重启路由器都没有效果
请问这个组合该如何使用.或者我的源码是不是不兼容

thanks!

**Comment by honwen** [comment]
only domain in [list](https://github.com/honwen/openwrt-dnsmasq-extra/blob/master/dnsmasq-extra/files/data/gfwlist) will be forward to smartdns

**Comment by honwen** [comment]
```bash
$ nslookup www.qq.com 192.168.1.1
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
www.qq.com	canonical name = public.sparta.mig.tencent-cloud.net.
Name:	public.sparta.mig.tencent-cloud.net
Address: 61.241.44.148
Name:	public.sparta.mig.tencent-cloud.net
Address: 157.255.192.44
```

```bash
$ nslookup www.google.com 192.168.1.1
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
Name:	www.google.com
Address: 216.58.220.196
```

**Comment by thisdk** [comment]
请问是不是不需要手动配置?
以下是我的配置图
![image](https://user-images.githubusercontent.com/23514168/71584204-9a08d380-2b4c-11ea-81ed-dccbfc2166ca.png)

**Comment by thisdk** [comment]
![image](https://user-images.githubusercontent.com/23514168/71584210-a856ef80-2b4c-11ea-9967-e3bbeaab684a.png)

**Comment by thisdk** [comment]
若是还原我的手动配置.会这样
![image](https://user-images.githubusercontent.com/23514168/71584377-3d59e880-2b4d-11ea-82f0-670ff9643df6.png)

**Comment by honwen** [comment]
DONT config `ANYTHING` manually, except  `/etc/config/dnsmasq-extra` `/etc/dnsmasq-extra.d/custom.conf`

**Comment by thisdk** [comment]
ok,thanks!

**Comment by honwen** [comment]
refer https://github.com/coolsnowwolf/lede/issues/2551
