### ISSUE TITLE
dns-forwarder出现问题

### ISSUE THREAD

**Issue by smaller09** [honwen/openwrt-dnsmasq-extra#26]
nslookup发现 dns-forwarder无法解释域名.
root@Router:~# nslookup www.163.com 127.0.0.1#8301
;; connection timed out; no servers could be reached
测试发现问题可能出现在ISP上，上游设为本机127.0.0.1:53就可以解释，上游设置成8.8.8.8或者9.9.9.9都无法解释。
奇怪的是通过ssr-tunnel也不行，无论是直接ssr-tunnel或者是dns-forwarder-》ssr-tunnel都无法解释域名。请大神调查一下。

**Comment by honwen** [comment]
CAN NOT REPRODUCE

**Comment by smaller09** [comment]
估计是dns-forwarder和openwrt的nightly有冲突，前两天刷了nightly就不行了。
目前用unbound替代。
用debian编译了一个dns-forwarder的x64版也一样转发不出去。之前测试上游设置为本机实际上也不行，是dns cache的干扰误判了。
目前也在查是不是isp的阻断。
