### ISSUE TITLE
can't run /etc/init.d/dnsmasq-extra update with openssl

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#29]
Hello@honwen
For some reason I have to use openssl instead of wolfss
![Screenshot from 2021-01-23 13-20-35](https://user-images.githubusercontent.com/10782586/105572808-62db1500-5d94-11eb-9d31-7cc16c37836a.png)

`BusyBox v1.31.1 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r15383+101-e1851720f1
 -----------------------------------------------------
root@OpenWrt:~# /etc/init.d/dnsmasq-extra update
Error relocating /usr/lib/libcurl.so.4: wolfSSL_ALPN_GetProtocol: symbol not found
Error relocating /usr/lib/libcurl.so.4: wolfSSL_UseALPN: symbol not found
Error relocating /usr/lib/libcurl.so.4: wolfSSL_ALPN_GetProtocol: symbol not found
Error relocating /usr/lib/libcurl.so.4: wolfSSL_UseALPN: symbol not found
Error relocating /usr/lib/libcurl.so.4: wolfSSL_ALPN_GetProtocol: symbol not found
Error relocating /usr/lib/libcurl.so.4: wolfSSL_UseALPN: symbol not found
Error relocating /usr/lib/libcurl.so.4: wolfSSL_ALPN_GetProtocol: symbol not found
Error relocating /usr/lib/libcurl.so.4: wolfSSL_UseALPN: symbol not found
Error relocating /usr/lib/libcurl.so.4: wolfSSL_ALPN_GetProtocol: symbol not found
Error relocating /usr/lib/libcurl.so.4: wolfSSL_UseALPN: symbol not found
Error relocating /usr/lib/libcurl.so.4: wolfSSL_ALPN_GetProtocol: symbol not found
Error relocating /usr/lib/libcurl.so.4: wolfSSL_UseALPN: symbol not found`

How to fix this?

thanks

**Comment by honwen** [comment]
try config `libcurl`

**Comment by jack338c** [comment]
it does't work ,it's selected by default 

![Screenshot from 2021-01-23 18-56-05](https://user-images.githubusercontent.com/10782586/105576316-e43ea180-5dac-11eb-8b6d-efcc39102d29.png)
