### ISSUE TITLE
Google doc and google home speaker issues

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#33]
Hi Chen

I found a weird issue: if choose dnsmasq-extra + ss(r)-tunnel (+dnsFtcp) ,Google doc and google home speaker work ok with any vps host

but if use others ,Google doc and google home speaker will not work sometime,it's denpend on vps host.but others application are ok,like youtube or google.com etc

Could you tell me how to fix this
 
thank you

**Comment by honwen** [comment]
> use others

what are those

**Comment by jack338c** [comment]
dnsmasq-extra + aiodns (recommended)

dnsmasq-extra + dcompass (experimental)

dnsmasq-extra + dnsproxy

dnsmasq-extra + smartdns

dnsmasq-extra + adguard-home

**Comment by honwen** [comment]
> Google doc
- can not reproduce
> google home speaker
- not have it


but u can try latest commit: https://github.com/honwen/openwrt-dnsmasq-extra/commit/e0d55856410b9e64a6a3acf37bec3413aa52882e

**Comment by jack338c** [comment]
OK,I will try 
I can't live without this reposity
many thanks :clinking_glasses:

**Comment by jack338c** [comment]
Sloved !:+1:

**Comment by jack338c** [comment]
Hi
I just tested  ,if run iptables -t nat -A PREROUTING -s 192.168.x.1/24 -p udp --dport 53 -j DNAT --to 192.168.x.1
iptables -t nat -A PREROUTING -s 192.168.x.1/24 -p tcp --dport 53 -j DNAT --to 192.168.x.1 the issue will be fixed.
this issue maybe caused by "etc/init.d/dnsmasq-extra rules"
thank you

**Comment by honwen** [comment]
try latest [commit](https://github.com/honwen/openwrt-dnsmasq-extra/commit/33d994fd3d073fc4d94066be2bb2fa87c802d88e),
maybe google home use `tcp` to query dns

https://github.com/honwen/openwrt-dnsmasq-extra/commit/33d994fd3d073fc4d94066be2bb2fa87c802d88e#diff-ff0ee720a1a790eb07730f94987b91ba68b5ddb921bb503f78af580697ffb8f5R365

**Comment by jack338c** [comment]
I will try @honwen 
many thanks!
