### ISSUE TITLE
请问是否存在优化？

### ISSUE THREAD

**Issue by TooTTooTTooT** [honwen/openwrt-dnsmasq-extra#34]
测试在E5-2690V4，RAM 512G以及GOLD 6246 RAM1024G虚拟环境或是硬环境下均出现处理器负载高。正常运行下实在戴尔R430 E5-2678V3 RAM 512G，处理器负载达到40-60之间，测试的两台服务器均出现同情况，初期以为是原版openwrt内核优化所致，后面换lean/lienol下编译dnsmasq-extra套组也是相同。

**Comment by honwen** [comment]
![image](https://user-images.githubusercontent.com/12322033/127629166-19cf700a-e208-4fca-88bb-5daa0ad6cc45.png)

![image](https://user-images.githubusercontent.com/12322033/127629113-8dc4d879-6ca3-40a0-89e1-54a30007ee57.png)


请提供以下文件, 用作分析
- /etc/config/dhcp
- /etc/dnsmasq.conf
- /etc/dnsmasq.d
- /var/dnsmasq.d
