### ISSUE TITLE
how to force a domain forward to proxy

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#35]
hi
Thanks for your great job
I tried put someting like ipset=/xxx.com/ssr_spec_dst_fw in custom.conf,but it's failed
Could you tell how to deal with this.
thanks for your time

**Comment by honwen** [comment]
is should works.

but ipset depends on dnsmasq, and cache-hit/restart/sth-else effect dnsmasq

so just put IPs to `ssr_spec_dst_fw`
![image](https://user-images.githubusercontent.com/12322033/129452383-5c205bd2-8da9-4004-8c13-50b58bb40fa1.png)

**Comment by jack338c** [comment]
thank you !

**Comment by jack338c** [comment]
@honwen 
Hi my idol,Now can I  force a domain forward to proxy by add something in custom.conf?
thanks for your support.

**Comment by honwen** [comment]
`ipset=/demo.com/ss_spec_dst_fw`
`ipset=/demo.com/ssr_spec_dst_fw`
`ipset=/demo.com/xray_spec_dst_fw`

depens on which prog used

**Comment by jack338c** [comment]
@honwen got it,Many thanks ,have a nice day :clinking_glasses:
