### ISSUE TITLE
ipset issue

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#36]
the file=/etc/init.d/shadowsocksr may have issues on ipset
if I try xray+openwrt-dnsmasq-extra,the custom.conf works ok

but if try ssr+openwrt-dnsmasq-extra.
1.work
ipset=/g.cn/ssr_spec_dst_fw
ipset=/g.cn/xray_spec_dst_fw

2 work(remove xray related)
ipset=/g.cn/ssr_spec_dst_fw

3 not work( change sort)
ipset=/g.cn/xray_spec_dst_fw
ipset=/g.cn/ssr_spec_dst_fw

Could you tested it  or give me any idea,thanks

**Comment by honwen** [comment]
maybe related to dnsmasq ver or ipset ver

**Comment by jack338c** [comment]
thanks
I tested it on lede1701 ,
I tryied compile shadowsocksr and luci-app-shadowsocksr for the neweset openwrt master .but it have errors

**Comment by honwen** [comment]
master is not recommanded

try latest release
