### ISSUE TITLE
got smartdns errors log in System Log

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#37]
I found this today ,Please help me to check it
thank you

Mon Jul 25 11:49:34 2022 daemon.err smartdns[32515]: gzip: can't open '/var/log/smartdns.log.pending.gz': Permission denied
Mon Jul 25 11:49:35 2022 daemon.err smartdns[32515]: gzip: can't open '/var/log/smartdns.log.pending.gz': Permission denied
Mon Jul 25 11:49:35 2022 daemon.err smartdns[32516]: gzip: can't open '/var/log/smartdns_cn.log.pending.gz': Permission denied
Mon Jul 25 11:49:38 2022 daemon.err smartdns[32516]: gzip: can't open '/var/log/smartdns_cn.log.pending.gz': Permission denied
Mon Jul 25 11:49:38 2022 daemon.err smartdns[32515]: gzip: can't open '/var/log/smartdns.log.pending.gz': Permission denied
Mon Jul 25 11:49:39 2022 daemon.err smartdns[32515]: gzip: can't open '/var/log/smartdns.log.pending.gz': Permission denied
Mon Jul 25 11:49:44 2022 daemon.err smartdns[32516]: gzip: can't open '/var/log/smartdns_cn.log.pending.gz': Permission denied
Mon Jul 25 11:49:45 2022 daemon.err smartdns[32516]: gzip: can't open '/var/log/smartdns_cn.log.pending.gz': Permission denied
Mon Jul 25 11:49:47 2022 daemon.err smartdns[32516]: gzip: can't open '/var/log/smartdns_cn.log.pending.gz': Permission denied
Mon Jul 25 11:49:47 2022 daemon.err smartdns[32515]: gzip: can't open '/var/log/smartdns.log.pending.gz': Permission denied
Mon Jul 25 11:49:48 2022 daemon.err smartdns[32516]: gzip: can't open '/var/log/smartdns_cn.log.pending.gz': Permission denied
Mon Jul 25 11:49:50 2022 daemon.err smartdns[32515]: gzip: can't open '/var/log/smartdns.log.pending.gz': Permission denied
Mon Jul 25 11:49:51 2022 daemon.err smartdns[32515]: gzip: can't open '/var/log/smartdns.log.pending.gz': Permission denied
Mon Jul 25 11:49:53 2022 daemon.err smartdns[32515]: gzip: can't open '/var/log/smartdns.log.pending.gz': Permission denied
Mon Jul 25 11:49:57 2022 daemon.err smartdns[32515]: gzip: can't open '/var/log/smartdns.log.pending.gz': Permission denied
Mon Jul 25 11:49:58 2022 daemon.err smartdns[32515]: gzip: can't open '/var/log/smartdns.log.pending.gz': Permission denied
Mon Jul 25 11:49:59 2022 daemon.err smartdns[32515]: gzip: can't open '/var/log/smartdns.log.pending.gz': Permission denied

**Comment by honwen** [comment]
related:
- https://github.com/pymumu/tinylog/issues/9
- https://github.com/pymumu/smartdns/commit/d3bbd8edd7c589e45ace9d597daf3d977df7685b

**Comment by honwen** [comment]
try latest commit

**Comment by jack338c** [comment]
@honwen I did already,it's working 
thanks 🥂
