### ISSUE TITLE
chatgpt

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#38]
Hi Master.
How can I open chatgpt website with your program
I enabled NULL - As Global Proxy in your program,but no luck
have a nice day !
![Screenshot 2023-02-17 at 9 55 28 AM](https://user-images.githubusercontent.com/10782586/219532263-64ebaea5-b2e0-4038-9da1-f01eb50db39c.png)

**Comment by honwen** [comment]
try latest commit

**Comment by jack338c** [comment]
just tried,still no luck,neither chinadns route model or As Global Proxy model

thanks

**Comment by honwen** [comment]
Ur IP seems a ip of Beijing?

chatgpt block chn itself

**Comment by jack338c** [comment]
yes,chatgpt block chn itself,but it works on vpn software by vpn Global Proxy model

I'm sure I have enabled Global Proxy model on my openwrt with your programe by checking [www.ip111.cn](http://www.ip111.cn/)
but still get Access denied by chatgpt

**Comment by honwen** [comment]
try disable `QUIC` in chrome://flags

**Comment by jack338c** [comment]
@jack338c 
Magical !
thanks a lot 🥂
