### ISSUE TITLE
can't startup dnsmasq in Openwrt 22.03

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#39]
Good day Master!
for some reason I need build openwrt-dnsmasq-extra in Openwrt 22.03
if remove conf-dir=/etc/dnsmasq.d from /etc/dnsmasq.conf ( https://github.com/openwrt/openwrt/issues/9726)
I got following log
![Screenshot 2023-05-14 at 9 14 52 AM](https://github.com/honwen/openwrt-dnsmasq-extra/assets/10782586/dd2c8503-5063-49fe-94e1-247f548ea616)
if add option confdir '/etc/dnsmasq-extra.d' in /etc/config/dhcp under config dnsmasq
then got this
![Screenshot 2023-05-14 at 9 17 32 AM](https://github.com/honwen/openwrt-dnsmasq-extra/assets/10782586/581ae67a-7682-4918-a167-896d2b44aa2b)

I have no idea to deal with this,Could you give me some tips?
thank you

![Screenshot 2023-05-14 at 9 15 52 AM](https://github.com/honwen/openwrt-dnsmasq-extra/assets/10782586/c733badf-ff16-432e-80a0-2b4a1c10bbc5)
![Screenshot 2023-05-14 at 9 18 00 AM](https://github.com/honwen/openwrt-dnsmasq-extra/assets/10782586/0e986c28-ba0c-4395-bdcc-674bb1c9f2b7)

**Comment by honwen** [comment]
why not [21.02.7](https://github.com/openwrt/openwrt/releases/tag/v21.02.7)

have not tested in `22.03` yet

**Comment by jack338c** [comment]
ok,I will try
Thanks

**Comment by jack338c** [comment]
@honwen 
Hello Master,if I have to  use your project (dnsmasq-extra )on openwrt 23.05(for ea7500 with nss driver) .where should be updated ?
your project is the best to me.please help me
thanks
