### ISSUE TITLE
twitter.com can not show some pictures under chnrouter 

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#4]
twitter.com can not show some pictures under chnrouter

**Comment by honwen** [comment]
any example?

**Comment by jack338c** [comment]
once you open twitter.com you will know what is going on,text is ok,just can't show image

**Comment by honwen** [comment]
In my env, it's all ok.

**Comment by jack338c** [comment]
@chenhw2 
that's interesting ! maybe it's my isp fault
anyway your repository is awesome ! thanks again !

**Comment by honwen** [comment]
U can try ```/etc/init.d/chinadns update``` to update chnroute manually.
