### ISSUE TITLE
can't open this website

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#40]
hi master
need your help,please have a look when you are convenient
I found it can't open this website (https://www.temu.com/) with openwrt-dnsmasq-extra+luci-app-xray
it will redirect automatically to following [website](https://www.temu.com/bgn_no_access.html?_x_channel_scene=spike&_x_channel_src=1&_x_sessn_id=ydv4v7gv1y&refer_page_name=lightning-deals&refer_page_id=10132_1696846621779_wl3kj37qqw&refer_page_sn=10132)(it's an icon ,not text)
I have try switch to global proxy model on luci-app-xray and even remove adblock file in openwrt-dnsmasq-extra,but no lucky.
![Screenshot 2023-10-09 at 6 25 58 PM](https://github.com/honwen/openwrt-dnsmasq-extra/assets/10782586/9f052b53-8c36-4451-84b0-4224de89cb87)

but  pc with software openclash can access this (https://www.temu.com/) without any issues

thanks

**Comment by honwen** [comment]
can not reproduce , try private mode

**Comment by jack338c** [comment]
sorry I don't catch your mean,I do use NCOGNITO/PRIVATE in chrome

**Comment by jack338c** [comment]
I recorded a screen [video](https://fu.ssgaff.cn:9876/api/public/dl/PUvWSu9D?inline=true),please check it

**Comment by honwen** [comment]
see https://updownradar.com/status/temu.com

**Comment by honwen** [comment]
try another region Tizi

**Comment by jack338c** [comment]
I tried jp ,us,it's same issue,both on pc and phone
but same jp,us on pc by vpn software is no problem

**Comment by jack338c** [comment]
by the way,I use smartdns@7700 with multidns/DoT/DoH,it takes smaller room space

Also tested aiodns and dnsproxy for this website.no lucky too

**Comment by jack338c** [comment]
this site [www.patpat.com](https://hk.patpat.com/) has same issue exactly
here is the screen [video](https://fu.ssgaff.cn:9876/api/public/dl/8dqC5pxP?inline=true)
thanks

**Comment by honwen** [comment]
try another PC?

**Comment by jack338c** [comment]
> try another PC?

tried on different pc and phone ,it's same

**Comment by jack338c** [comment]
dnsmasq-extra +cdns+ssr has the same issue too,just tested

**Comment by honwen** [comment]
> try another region Tizi

can u share Ur Tizi to me for testing?

**Comment by jack338c** [comment]
here is
![Screenshot 2023-10-11 at 10 51 27 AM](https://github.com/honwen/openwrt-dnsmasq-extra/assets/10782586/0d60d3e8-6b2f-4aed-84df-3676ee7a4be1)
xNFCb8tYmDqv

**Comment by honwen** [comment]
got it , will test it later

**Comment by jack338c** [comment]
👍

**Comment by honwen** [comment]
interesting, still CAN NOT reproduce Ur problem

![image](https://github.com/honwen/openwrt-dnsmasq-extra/assets/12322033/b4ba2204-94ed-423a-ac5e-8abe53b6563a)
![image](https://github.com/honwen/openwrt-dnsmasq-extra/assets/12322033/b58fe714-aa57-4e29-b1e5-ac09ece9e052)

**Comment by jack338c** [comment]
this is really weird
I tested it in different network environment,like LTE network(smartphone hotspot),but no lucky
my openwrt version for luci-xray is OpenWrt 21.02.2 r16495-bf0c965af0 (linksys EA6350)
luci-ssr is LEDE Reboot 17.01-SNAPSHOT r4046-beaa2ecc10(TP-Link TL-MR22U v1)
the only different is [here](https://github.com/honwen/luci-app-xray/issues/9)
Thank you very much for your help

**Comment by jack338c** [comment]
@honwen 
Today I do a clean installing for everthing ,you are right.it's my mistaken
thanks for your patience
You are the best 💯

**Comment by jack338c** [comment]
the last issue was my luci-xray,other packages are no problem
but luci-ssr still have this issue.I did't figure out yet
