### ISSUE TITLE
how to force a domain Bypass proxy

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#41]
Master,I can't open this [website](https://portal.ustraveldocs.com),neither on vpn software.but it can be open with no proxy network environment

I tried updated custom.conf or direct to fix it.but no lucky.
Finally by adding 172.64.153.244  and 104.18.34.12 into Bypass ip list to fix it
but I think the ip should be like 172.64.153.244/xx and 104.18.34.12/xx
is that correct? I'm not sure,could you tell me something 
Thank you

`jack6@jack6s-Mac-mini ~ % nslookup portal.ustraveldocs.com
Server:		10.20.30.40
Address:	10.20.30.40#53

Non-authoritative answer:
portal.ustraveldocs.com	canonical name = portal.ustraveldocs.com.cdn.cloudflare.net.
Name:	portal.ustraveldocs.com.cdn.cloudflare.net
Address: 172.64.153.244
Name:	portal.ustraveldocs.com.cdn.cloudflare.net
Address: 104.18.34.12

jack6@jack6s-Mac-mini ~ % nslookup portal.ustraveldocs.com
Server:		10.20.30.40
Address:	10.20.30.40#53

Non-authoritative answer:
portal.ustraveldocs.com	canonical name = portal.ustraveldocs.com.cdn.cloudflare.net.
Name:	portal.ustraveldocs.com.cdn.cloudflare.net
Address: 172.64.153.244`

**Comment by honwen** [comment]
```
ipset=/g.cn/ss_spec_dst_bp
ipset=/g.cn/ssr_spec_dst_bp
ipset=/g.cn/xray_spec_dst_bp
```

**Comment by jack338c** [comment]
got it 
many thanks!

**Comment by jack338c** [comment]
> ```
> ipset=/g.cn/ss_spec_dst_bp
> ipset=/g.cn/ssr_spec_dst_bp
> ipset=/g.cn/xray_spec_dst_bp
> ```

Hello master
the default parameter in custom.conf is "spec_dst_fw",I wonder whether  spec_dst_bp and spec_dst_fw both works ?
`ipset=/g.cn/ss_spec_dst_fw
ipset=/g.cn/ssr_spec_dst_fw
ipset=/g.cn/xray_spec_dst_fw`

Recently I try added some domains rules by spec_dst_fw or  spec_dst_bp  in custom.conf for testing
but it doesn't work as my purpose
for spec_dst_bp,I veryfiy it by checking misc_direct.conf file
and spec_dst_fw by ipset list xray_spec_dst_fw
neither of them can show the domains or ips 
I don't know where is problem,Could you tell me something
appreciate your help
