### ISSUE TITLE
question about dns-forward

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#6]
Hi Chen
I'm trying your newest one for "openwrt-dnsmasq-extra" it looks more fast
I did not find any dns-forwarder file in config and init.d folder this time
but I find dns-forwarder is listing on udp 7301 and udp 7302
Could you tell me how it works on both tcp and udp 

thank you

**Comment by honwen** [comment]
```dns-forwarder``` and ```cdns``` now are started by ```chinadns```,
config is ```ww_dns``` in [chinadns.config](https://github.com/chenhw2/openwrt-dnsmasq-extra/blob/master/chinadns/files/chinadns.config), you can add more DNS as you like

```dns-forwarder``` only work on udp.

**Comment by jack338c** [comment]
Beautiful!
Thanks for keep updating on this awesome repository

**Comment by honwen** [comment]
Thanks, too.
