### ISSUE TITLE
I have a Error

### ISSUE THREAD

**Issue by TsLenMo** [honwen/openwrt-dnsmasq-extra#7]
make[4]: Entering directory '/DiskA/OpenWrt/lede-sdk-17.01.4/build_dir/target-arm_cortex-a53+neon-vfpv4_musl-1.1.16_eabi/cdns/cdns-2016-11-29'
ccache_cc -c -o main.o main.c -Os -pipe -mcpu=cortex-a53 -mfpu=neon-vfpv4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -iremap /DiskA/OpenWrt/lede-sdk-17.01.4/build_dir/target-arm_cortex-a53+neon-vfpv4_musl-1.1.16_eabi/cdns//cdns-2016-11-29:cdns-2016-11-29 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/DiskA/OpenWrt/lede-sdk-17.01.4/staging_dir/target-arm_cortex-a53+neon-vfpv4_musl-1.1.16_eabi/usr/include -I/DiskA/OpenWrt/lede-sdk-17.01.4/staging_dir/target-arm_cortex-a53+neon-vfpv4_musl-1.1.16_eabi/include -I/DiskA/OpenWrt/lede-sdk-17.01.4/staging_dir/toolchain-arm_cortex-a53+neon-vfpv4_gcc-5.4.0_musl-1.1.16_eabi/usr/include -I/DiskA/OpenWrt/lede-sdk-17.01.4/staging_dir/toolchain-arm_cortex-a53+neon-vfpv4_gcc-5.4.0_musl-1.1.16_eabi/include/fortify -I/DiskA/OpenWrt/lede-sdk-17.01.4/staging_dir/toolchain-arm_cortex-a53+neon-vfpv4_gcc-5.4.0_musl-1.1.16_eabi/include  -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600
main.c:28:18: fatal error: argp.h: No such file or directory
compilation terminated.
Makefile:13: recipe for target 'main.o' failed
make[4]: *** [main.o] Error 1
make[4]: Leaving directory '/DiskA/OpenWrt/lede-sdk-17.01.4/build_dir/target-arm_cortex-a53+neon-vfpv4_musl-1.1.16_eabi/cdns/cdns-2016-11-29'
Makefile:49: recipe for target '/DiskA/OpenWrt/lede-sdk-17.01.4/build_dir/target-arm_cortex-a53+neon-vfpv4_musl-1.1.16_eabi/cdns//cdns-2016-11-29/.built' failed
make[3]: *** [/DiskA/OpenWrt/lede-sdk-17.01.4/build_dir/target-arm_cortex-a53+neon-vfpv4_musl-1.1.16_eabi/cdns//cdns-2016-11-29/.built] Error 2
make[3]: Leaving directory '/DiskA/OpenWrt/lede-sdk-17.01.4/package/feeds/openwrt-dnsmasq-extra/cdns'
package/Makefile:105: recipe for target 'package/feeds/openwrt-dnsmasq-extra/cdns/compile' failed
make[2]: *** [package/feeds/openwrt-dnsmasq-extra/cdns/compile] Error 2
make[2]: Leaving directory '/DiskA/OpenWrt/lede-sdk-17.01.4'
package/Makefile:101: recipe for target '/DiskA/OpenWrt/lede-sdk-17.01.4/staging_dir/target-arm_cortex-a53+neon-vfpv4_musl-1.1.16_eabi/stamp/.package_compile' failed
make[1]: *** [/DiskA/OpenWrt/lede-sdk-17.01.4/staging_dir/target-arm_cortex-a53+neon-vfpv4_musl-1.1.16_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/DiskA/OpenWrt/lede-sdk-17.01.4'
/DiskA/OpenWrt/lede-sdk-17.01.4/include/toplevel.mk:191: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by TsLenMo** [comment]
Can you tell me what wrong whit this?

**Comment by honwen** [comment]
```main.c:28:18: fatal error: argp.h: No such file or directory```

Double check Ur build environment.

**Comment by honwen** [comment]
I noticed that U built this package using SDK.

Try full [buildsystem](https://github.com/lede-project/source/tree/v17.01.4), instead of SDK.

**Comment by TsLenMo** [comment]
ok,I try agin

**Comment by TsLenMo** [comment]
I using full build System then it's OK.

**Comment by honwen** [comment]
Great

**Comment by TsLenMo** [comment]
root@Raspberry-Pi-3B:/overlay/DownLoad# opkg install *
Unknown package 'ChinaDNS'.
Unknown package 'Ruisi-master.zip'.
Unknown package 'cdns'.
Unknown package 'http-dns'.


but  It's Can't install ...
