### ISSUE TITLE
how about dnsmasq-extra + dnscrypt

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-dnsmasq-extra#8]
Sir
If I chiosed dnsmasq-extra + dnscrypt,dose this mean I should uncheck chinadns +cdns +dns-forwarder in make menuconfig? and udp function will  not be available?

or just select all in make menuconfig

I almost focus on your repository every week,It's my favorite repository

thank you for sharing this wonderful stuf!

**Comment by honwen** [comment]
if ```chinadns +cdns +dns-forwarder``` works well in Ur env, ```chinadns +cdns +dns-forwarder``` is better.

```dnscrypt``` is for ***very critical*** DNS poisoning.

**Comment by jack338c** [comment]
@chenhw2 
Ok,I understand now 
thanks for your help

**Comment by honwen** [comment]
btw, ```dnscrypt``` is too big (>2.5Mbytes) for normal openwrt, and slow after OS just boot.

**Comment by jack338c** [comment]
@chenhw2 
ok,I got it
